name: authx
description: A simple and flexible authentication library for Dart applications supporting multiple OAuth providers with type-safe provider management.
version: 1.0.1
repository: https://github.com/yuen-quinn/authx
homepage: https://github.com/yuen-quinn/authx
issue_tracker: https://github.com/yuen-quinn/authx/issues
documentation: https://github.com/yuen-quinn/authx/blob/main/README.md

environment:
  sdk: ^3.10.7

dependencies:
  http: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
